In [2]:
import numpy as np 

In [11]:
minhaLista = [1, 2, 3, 4, 5, 6, 7]

In [12]:
minhaLista

[1, 2, 3, 4, 5, 6, 7]

In [9]:
meuArray = np.array(minhaLista)
meuArray

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
print(meuArray)

[1 2 3 4 5 6 7]


In [13]:
minhaLista = list(range(9))

In [14]:
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [15]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
array3 = np.arange(0, 10, 0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [22]:
newArray = np.around(array3)
newArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [24]:
array3 = np.arange(0, 10, 0.5, dtype = int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
array4 = np.arange(12)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [28]:
type(array4)

numpy.ndarray

In [29]:
array4.dtype #ou print(array4.dtype)

dtype('float64')

In [30]:
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

[0 1 2 3 4]


In [31]:
vetor1[3]

3

In [33]:
vetor1[0:2]

array([0, 1])

In [34]:
print(vetor1[0:2])

[0 1]


In [35]:
s = np.array(['python', 'profissinal', 'java', 'agua'])
s

array(['python', 'profissinal', 'java', 'agua'], dtype='<U11')

In [38]:
s = np.array(['python', 12345, 'profissinal', 'java', 'agua', 'ya ki'])
s

array(['python', '12345', 'profissinal', 'java', 'agua', 'ya ki'],
      dtype='<U21')

In [43]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [45]:
vetor1[0] = "novo elemento"
vetor1

ValueError: ignored

In [46]:
vetor1[0] = 0
vetor1

array([ 0,  1, 10,  3,  4])